# Generated by Django 2.2.5 on 2019-09-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationweather',
            name='weather',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='locationweather',
            name='lat',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='locationweather',
            name='long',
            field=models.FloatField(default=1.0),
        ),
    ]
