# Generated by Django 2.2.5 on 2019-09-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190908_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationweather',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='weather.User'),
        ),
    ]
