# Generated by Django 2.2.5 on 2019-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190908_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationweather',
            old_name='city',
            new_name='location_querry',
        ),
        migrations.AddField(
            model_name='locationweather',
            name='location',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
