# Generated by Django 2.2.5 on 2019-09-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20190908_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationweather',
            old_name='weather',
            new_name='weather_summary',
        ),
        migrations.AddField(
            model_name='locationweather',
            name='weather_temperature',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
